DEFAULTS = {
    'app_name': 'partnership_analysis_system',
    'environment': 'production',
    'debug': False,
    'carbone_api_key': '',
    'google_genai_api_key': '',
    'research_max_queries_per_gap': 3,
    'research_cache_ttl_days': 30,
    'research_confidence_threshold': 0.70,
    'extraction_confidence_threshold': 0.75,
    'extraction_flag_low_confidence': True,
    'financial_discount_rate': 0.10,
    'financial_capex_amortization_months': 48,
    'financial_sensitivity_variance': 0.20,
    'input_dir': './inputs',
    'output_dir': './outputs',
    'cache_dir': './cache',
    'templates_dir': './templates',
    'logs_dir': './logs',
    'cache_backend': 'json_file',
    'cache_file_path': './cache/research_cache.json',
    'cache_auto_cleanup_days': 90,
    'web_search_timeout': 30,
    'log_level': 'INFO',
    'log_format': 'json',
    'log_file': './logs/execution.log',
    'schema_version': '1.0',
    'schema_strict_mode': True,
    'brand_name': "Konsulin",
    'brand_about': "Providing booking management system through WhatsApp",
    'brand_address': "Jakarta",
    'brand_industry': "IT Service",
    'deep_research_max_iterations': 3,
    'deep_research_model_search': 'gemini-2.0-flash',
    'deep_research_model_synthesis': 'gemini-2.5-flash',
    'deep_research_model_questions': 'gemini-2.5-flash',
    'deep_research_iteration_timeout': 300,
    'deep_research_cache_ttl_days': 7,
    'deep_research_gap_threshold': 3
}
