DEFAULTS = {
    'APP_NAME': 'partnership_analysis_system',
    'ENVIRONMENT': 'production',
    'DEBUG': False,
    'CARBONE_API_KEY': '',
    'GOOGLE_GENAI_API_KEY': '',
    'RESEARCH_MAX_QUERIES_PER_GAP': 3,
    'RESEARCH_CACHE_TTL_DAYS': 30,
    'RESEARCH_CONFIDENCE_THRESHOLD': 0.70,
    'EXTRACTION_CONFIDENCE_THRESHOLD': 0.75,
    'EXTRACTION_FLAG_LOW_CONFIDENCE': True,
    'FINANCIAL_DISCOUNT_RATE': 0.10,
    'FINANCIAL_CAPEX_AMORTIZATION_MONTHS': 48,
    'FINANCIAL_SENSITIVITY_VARIANCE': 0.20,
    'INPUT_DIR': './inputs',
    'OUTPUT_DIR': './outputs',
    'CACHE_DIR': './cache',
    'TEMPLATES_DIR': './templates',
    'LOGS_DIR': './logs',
    'CACHE_BACKEND': 'json_file',
    'CACHE_FILE_PATH': './cache/research_cache.json',
    'CACHE_AUTO_CLEANUP_DAYS': 90,
    'LOG_LEVEL': 'INFO',
    'LOG_FORMAT': 'json',
    'LOG_FILE': './logs/execution.log',
    'SCHEMA_VERSION': '1.0',
    'SCHEMA_STRICT_MODE': True,
    'BRAND_NAME': "Konsulin",
    'BRAND_ABOUT': "Providing booking management system through WhatsApp",
    'BRAND_ADDRESS': "Jakarta",
    'BRAND_INDUSTRY': "IT Service"
}
